### ISSUE TITLE
Sphinx server configuration file

### ISSUE THREAD

**Issue by quentinus95** [dldl/sphinx-server#6]
Add support for a Sphinx configuration file to remove the _.credentials_, _.gitignore_ and env vars requirement.

File: _.sphinx-server.yml_
Structure example:

``` yml
credentials:
    username: user
    password: pwd
ignore:
    - .git/
    - another.file
environment: dev
```

The default values if the file or one section is missing:

``` yml
credentials: ~
ignore:
    - .git/
environment: prod
```

Thx !

**Comment by quentinus95** [comment]
I have renamed _sphinx-config_ file to _sphinx-server_.

**Comment by quentinus95** [comment]
Some changes:

Default file in this repository (on /):

``` yml
credentials:
    username: ~
    password: ~
ignore:
    - .git/
autobuild: false
```

Moved to /opt/sphinx-server (with the server.py).

Then, the user can change this configuration by adding a _.sphinx-server.yml_ file at root of his documentation (in web/):

``` yml
credentials:
    username: user
    password: pass
ignore:
    - .git/
    - anotherfile
autobuild: true
```

Both files must be parsed, the second generated array (dictionaries) will erase values in the first one (recursively).

https://stackoverflow.com/questions/38987/how-to-merge-two-python-dictionaries-in-a-single-expression
